#############################################################################
## Crytek Source File
## Copyright (C) 2013, Crytek Studios
##
## Creator: Christopher Bolte
## Date: Oct 31, 2013
## Description: WAF  based build system
#############################################################################

def build(bld):	
	files = bld.read_file_list('webpanelplugin.waf_files')

	bld.CryPlugin(
		target = 'WebPanelPlugin',
		source = files,
		features = 'qt',
		lib = [ 'Qt5WebKit', 'Qt5WebKitWidgets' ],
		use = 'EditorCommon',
		qt_to_moc_files = [ 'WebPanel.h' ]
	)