//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Utility.rc
//
#define IDS_CLASSNAME                   1
#define IDS_PARAMETERS                  2
#define IDS_CLASS_NAME                  3
#define IDS_LIBDESC                     4
#define IDS_CATEGORY                    5
#define IDS_SIMPLE                      6
#define IDS_NONAME                      7
#define IDS_OBJECTS                     8
#define IDS_EXPORT                      9
#define IDS_OPTIONS                     10
#define IDS_TIMING                      11
#define IDS_MATERIAL                    12
#define IDS_PHYSICS                     13
#define IDS_BATCH                       14
#define IDB_BUTTON_MAPS                 101
#define IDD_IMPORT_PANEL                101
#define IDD_SKELUTIL                    102
#define IDD_EXPORT                      102
#define IDD_NODES                       103
#define IDB_BUTTONS                     103
#define IDB_BUTTONS_MASK                104
#define IDD_NAMED_RANGES                105
#define IDD_FACEREPORT                  108
#define IDD_PROGRESS                    111
#define IDD_ABOUT                       112
#define IDD_BONES                       113
#define IDD_OPTIONS                     115
#define IDD_MA                          116
#define IDD_TIMING                      117
#define IDB_DMTL_BUTTONS                122
#define IDB_DMTL_MASKBUTTONS            123
#define IDC_SH_EDIT                     216
#define IDC_SS_EDIT                     217
#define IDC_SI_EDIT                     219
#define IDC_TR_EDIT                     220
#define IDC_SHOP_EDIT                   221
#define IDC_SH_SPIN                     326
#define IDC_SS_SPIN                     327
#define IDC_SI_SPIN                     329
#define IDC_TR_SPIN                     330
#define IDC_SHOP_SPIN                   331
#define IDC_BTN1                        1000
#define IDC_EXPORT_BTN                  1000
#define IDC_CLOSE                       1001
#define IDC_WRITE_GEOM                  1001
#define IDC_IMPORT_MESH                 1001
#define IDC_WRITE_HIER                  1002
#define IDC_IMPORT_LIGHT                1002
#define IDC_WRITE_BONE_ANIM             1003
#define IDC_IMPORT_HELPER               1003
#define IDC_ROTATE_TO_WORLD_CS          1003
#define IDC_SIMPLE_EDIT                 1004
#define IDC_BONE_ANIM_FR_EDIT           1004
#define IDC_MERGE_SCENE                 1004
#define IDC_WRITE_VERT_ANIM             1005
#define IDC_REPLACE_SCENE               1005
#define IDC_KEY_CLEANUP_ROTATION        1005
#define IDC_SIMPLE_SPIN                 1006
#define IDC_BONE_ANIM_FR_SPIN           1006
#define IDC_WRITE_WEIGHTS               1007
#define IDC_KEY_CLEANUP_ROTATION_SPIN   1007
#define IDC_BONE_ANIM_KEYS              1008
#define IDC_WRITE_WEIGHTS2              1008
#define IDC_GENERATE_DEFAULT_UVS        1008
#define IDC_BONE_ANIM_EVERY             1009
#define IDC_VERT_ANIM_KEYS              1010
#define IDC_KEY_CLEANUP_POSITION        1010
#define IDC_VERT_ANIM_EVERY             1011
#define IDC_KEY_CLEANUP_POSITION_SPIN   1011
#define IDC_WRITE_MATERIALS             1012
#define IDC_SIMPLE_EDIT2                1013
#define IDC_VERT_ANIM_FR_EDIT           1013
#define IDC_SIMPLE_SPIN2                1014
#define IDC_VERT_ANIM_FR_SPIN           1014
#define IDC_ANIM_START_EDIT             1015
#define IDC_WRITE_GEOMETRY              1015
#define IDC_WRITE_COMBINED_FILE         1016
#define IDC_ANIM_START_SPIN             1016
#define IDC_MORPH_MIN_OFFSET            1016
#define IDC_MORPH_MIN_OFFSET_EDIT       1016
#define IDC_WRITE_SEPARATE_FILES        1017
#define IDC_OBJ_LIST                    1017
#define IDC_ANIM_END_EDIT               1017
#define IDC_WRITE_GEOM_WS               1018
#define IDC_BONE_LIST                   1018
#define IDC_MORPH_MIN_OFFSET_SPIN       1018
#define IDC_RIGID                       1019
#define IDC_VA_END_EDIT                 1019
#define IDC_BLEND                       1020
#define IDC_CHECK3                      1021
#define IDC_INDIVIDUALFILES             1021
#define IDC_ANIM_END_SPIN               1022
#define IDC_MERGE_NODES                 1022
#define IDC_ALLOW_MULTIUV               1023
#define IDC_BUILD_NO                    1024
#define IDC_VERTANIM_WS                 1024
#define IDC_PROGRESS                    1024
#define IDC_IGNORE_MESH_BONES           1027
#define IDC_NODE_CLEAR                  1028
#define IDC_ENABLE_KEY_CLEANUP          1028
#define IDC_NODE_ADD_SEL                1029
#define IDC_MANUAL_RANGE                1029
#define IDC_1LINK                       1030
#define IDC_BONE_ADD_SEL                1030
#define IDC_NLINKS                      1031
#define IDC_ADD_RELATED_BONES           1033
#define IDC_VA_MANUAL_RANGE             1034
#define IDC_VA_START_EDIT               1035
#define IDC_VA_START_SPIN               1036
#define IDC_VA_END_SPIN                 1037
#define IDC_ADD_WHOLE_SKEL              1038
#define IDC_MAPON_TR                    1038
#define IDC_BONE_CLEAR                  1039
#define IDC_BONE_REMOVE                 1040
#define IDC_BONE_ADD                    1041
#define IDC_EXPORT_BONES                1044
#define IDC_INTER_ADD                   1045
#define IDC_NODE_ADD                    1045
#define IDC_CHILD_TIMES                 1045
#define IDC_EXPORT_NODES                1046
#define IDC_PARENT_TIMES                1046
#define IDC_STABILIZE_FEET              1047
#define IDC_AUTO_SAVE                   1048
#define IDC_LOAD                        1049
#define IDC_LOCK_AD                     1049
#define IDC_SAVE                        1050
#define IDC_LOCK_DS                     1050
#define IDC_RESET                       1051
#define IDC_SAVE_DEFAULT                1052
#define IDC_WARN_NONRGID                1053
#define IDC_WARN_ORPHAN_TV              1054
#define IDC_LOCK_ADTEX                  1054
#define IDC_WARN_DLL                    1055
#define IDC_WRITE_VCOL                  1056
#define IDC_WARN_MULTI_VCOL             1057
#define IDC_WARN_OFFAXIS_SCL            1058
#define IDC_EDIT_NAMED_SEG              1058
#define IDC_INTER_REMOVE                1060
#define IDC_NODE_REMOVE                 1060
#define IDC_INTER_CLEAR                 1061
#define IDC_RANGE_LIST                  1061
#define IDC_MAPON_SH                    1061
#define IDC_START_ED                    1062
#define IDC_HIGHLIGHT                   1062
#define IDC_START_SP                    1063
#define IDC_END_ED                      1064
#define IDC_END_SP                      1065
#define IDC_NAME                        1066
#define IDC_DELETE                      1067
#define IDC_OK                          1068
#define IDC_PREVIEW_NODES               1069
#define IDD_CRY_SHADER                  1069
#define IDC_PREVIEW_GAME                1070
#define IDD_MATERIAL                    1070
#define IDD_PHYSICS                     1071
#define IDC_EXPORT_NODES_COLLADA        1071
#define IDC_ANIM_NAME                   1072
#define IDD_BATCH                       1072
#define IDC_EXPORTNEW                   1073
#define IDC_BUILDING                    1075
#define IDC_WORLDCS                     1076
#define IDC_BUILDING2                   1076
#define IDC_PHYSICALIZE                 1077
#define IDC_NO_SHADOWS                  1078
#define IDC_NOSHADOWS                   1078
#define IDC_MATEDIT                     1079
#define IDC_PICKSELECTEDMATERIAL        1080
#define IDC_CREATEMATERIAL              1081
#define IDC_PREVIEW_EXPLORE             1081
#define IDC_EXPORT_TO                   1082
#define IDC_EXP_MAT_SYNC                1083
#define IDC_EXP_MAT_SYNC_TO_EDITOR      1084
#define IDC_CUSTOM1                     1085
#define IDC_CUSTOMFILENAME              1085
#define IDC_CUSTOM2                     1086
#define IDC_BREAKABLE_PHISICS           1087
#define IDC_BREAKABLE_PHYSICS           1087
#define IDC_GRANULARITY                 1088
#define IDC_MODE                        1091
#define IDC_BATCH                       1092
#define IDC_SH_2                        1093
#define IDC_SH_AMBIENT                  1094
#define IDC_USECUSTOMFILENAME           1096
#define IDC_CUSTOMFILENAMEEDIT          1098
#define IDC_CHECK1                      1099
#define IDC_FILE_PER_SUBRANGE           1099
#define IDC_SORT_BONES                  1099
#define IDC_TEXT                        1100
#define IDC_MESSAGE                     1101
#define IDC_ICONCTRL                    1102
#define IDC_CUSTOMFILENAMEENTER         1103
#define IDC_MAPON_DI                    1104
#define IDC_BUTTON1                     1104
#define IDC_SELECT_DEGENERATE_FACES     1104
#define IDC_TEST                        1104
#define IDC_TESTSUITE                   1104
#define IDC_COPY_RANGES_TO_TIME_TAGS    1104
#define IDC_MAPON_SP                    1105
#define IDC_STD_COLOR1                  1109
#define IDC_STD_COLOR2                  1113
#define IDC_STD_COLOR3                  1114
#define IDC_SHADER                      1728
#define IDC_SURFACE                     1729
#define IDC_SPEC_TEXT                   1863
#define IDC_ALPHATEST_EDIT              1891
#define IDC_ALPHATEST_SPIN              1892
#define IDC_ADDITIVE                    1896
#define IDC_SHADER_DESC                 1897
#define IDC_SHADER_REQUIREMENTS         1898
#define IDC_ADDITIVE_DECAL              1899
#define IDC_ADDITIVE_DECAL2             1900
#define IDC_ALPHA_BLEND                 1900
#define IDC_ADDITIVE_DECAL3             1901
#define IDC_COLOR1                      2030
#define IDC_COLOR2                      2031
#define IDC_USEGLOSSINESS               2032
#define IDC_SETUPRC                     2033
#define IDS_DS_AMBIENT                  10045
#define IDS_DS_DIFFUSE                  10046
#define IDS_DS_SPECULAR                 10047
#define IDS_CGF_FILETYPE_STRING         10048
#define IDS_CHR_FILETYPE_STRING         10049
#define IDS_CGA_FILETYPE_STRING         10050
#define IDS_ANM_FILETYPE_STRING         10051
#define IDS_DS_PARAMETERS               10122
#define IDS_DS_PARAMCHG                 10183
#define IDS_DS_LOCKAD                   11443
#define IDS_DS_LOCKCOL                  11444
#define IDS_DS_LOCK_DS                  11460
#define IDS_DS_MTLDESC                  11470
#define IDS_DS_NOSUCH_CLR               11533
#define IDS_KE_SPEC_LEVEL               11549
#define IDS_KE_GLOSSINESS               11557
#define IDS_KE_SELFILLUM                11562
#define IDS_JW_ADTEXLOCK                11620
#define IDS_JW_ADLOCK                   11625
#define IDS_JW_DSLOCK                   11626
#define ID_BUTTON40001                  40001
#define ID_BUTTON40002                  40002
#define IDS_KE_SH_OPACITY_LEVEL         40003
#define IDC_SH                          40004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        109
#define _APS_NEXT_COMMAND_VALUE         40003
#define _APS_NEXT_CONTROL_VALUE         1105
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
