#############################################################################
## Crytek Source File
## Copyright (C) 2006, Crytek Studios
##
## Creator: Sascha Demetrio
## Date: Jul 31, 2006
## Description: GNU-make based build system
#############################################################################

PROJECT_TYPE := module
PROJECT_VCPROJ := GameDllCrysis2.vcproj

PROJECT_CPPFLAGS_COMMON := \
	-I$(CODE_ROOT)/CryEngine/CryCommon \
	-I$(CODE_ROOT)/CryEngine/CryAction \
	-DPROFILE -D_PROFILE

PROJECT_SOURCES_CPP_REMOVE := \
	StdAfx.cpp \
	OrganicMotion/%.cpp

ifeq ($(MKOPTION_UNITYBUILD),1)
PROJECT_SOURCES_CPP_REMOVE += \
	PlayerVisTable.cpp \
	WeaponAttachmentManager.cpp \
	CameraModes.cpp \
	PlayerCamera.cpp \
	MindControl.cpp \
	MindControlConsole.cpp \
	MindControlInput.cpp \
	CoverAndLean.cpp \
	CoverAndLeanDraw.cpp \
	CoverAndLeanMath.cpp \
	MountedGunController.cpp \
	StealthKill.cpp \
	InteractiveActionController.cpp \
	AutoAimManager.cpp \
	HitDeathReactions.cpp \
	HitDeathReactionsSystem.cpp \
	ScriptBind_HitDeathReactions.cpp \
	Alien.cpp \
	CompatibilityAlienMovementController.cpp \
	Hunter.cpp \
	Observer.cpp \
	Scout.cpp \
	Trooper.cpp \
	GrabHandler.cpp \
	NanoModeArmor.cpp \
	NanoModePower.cpp \
	NanoModeStealth.cpp \
	NanoModeTactical.cpp \
	NanoSuit_v2.cpp \
	NanoSuitEnergy.cpp \
	NanoSuitParams.cpp \
	SuitShapeDeformation.cpp \
	Harvester.cpp \
	Pinger.cpp \
	Pinger_Mechanics.cpp \
	Pinger_Movement.cpp \
	PingerMovementController.cpp \
	Spotter.cpp \
	Spotter_Movement.cpp \
	SpotterMovementController.cpp \
	Audio/AudioSignalPlayer.cpp \
	Audio/GameAudio.cpp \
	Audio/Scriptbind_GameAudio.cpp \
	EditorGame.cpp \
	EquipmentSystemInterface.cpp \
	ClientGameTokenSynch.cpp \
	ClientSynchedStorage.cpp \
	Game.cpp \
	GameActions.cpp \
	GameCVars.cpp \
	GameFactory.cpp \
	Radio.cpp \
	ScriptBind_Game.cpp \
	ScriptControlledPhysics.cpp \
	ServerGameTokenSynch.cpp \
	ServerSynchedStorage.cpp \
	SPAnalyst.cpp \
	SynchedStorage.cpp \
	TacticalManager.cpp \
	Voting.cpp \
	Environment/AlienMine.cpp \
	Environment/BattleDust.cpp \
	Environment/LedgeManager.cpp \
	Environment/Shake.cpp \
	Environment/FlowTornado.cpp \
	Environment/Tornado.cpp \
	Environment/InteractiveObject.cpp \
	Environment/InteractiveObjectRegistry.cpp \
	Environment/ScriptBind_InteractiveObject.cpp \
	Environment/AlienDropPod.cpp \
	Environment/FlowAlienDropPodNodes.cpp \
	BlendedEffect.cpp \
	BlendNode.cpp \
	ScreenEffects.cpp \
	ScreenEffects_Game.cpp \
	ActorParametersRegistry.cpp \
	BasicActorParameters.cpp \
	GameParameters.cpp \
	ItemSharedParams.cpp \
	WeaponSharedParams.cpp \
	VehicleClient.cpp \
	VehicleMovementTweaks.cpp \
	Vehicle/VehicleViewGameBase.cpp \
	Vehicle/VehicleViewSteer.cpp \
	VehicleMovementAmphibious.cpp \
	VehicleMovementArcadeWheeled.cpp \
	VehicleMovementBase.cpp \
	VehicleMovementHelicopter.cpp \
	VehicleMovementHovercraft.cpp \
	VehicleMovementStdBoat.cpp \
	VehicleMovementStdWheeled.cpp \
	VehicleMovementTank.cpp \
	VehicleMovementVTOL.cpp \
	VehicleDamageBehaviorBurn.cpp \
	VehicleDamageBehaviorCameraShake.cpp \
	VehicleDamageBehaviorCollisionEx.cpp \
	VehicleDamageBehaviorExplosion.cpp \
	VehicleDamageBehaviorTire.cpp \
	VehicleActionAutomaticDoor.cpp \
	VehicleActionDeployRope.cpp \
	BasicEventListener.cpp \
	GameDll.cpp \
	GameStartup.cpp \
	Actor.cpp \
	ActorDamageEffectController.cpp \
	ActorRef.cpp \
	AIDemoInput.cpp \
	ScriptBind_Actor.cpp \
	Shark.cpp \
	SharkMovementController.cpp \
	BodyDamage.cpp \
	GodMode.cpp \
	NetPlayerInput.cpp \
	PerkSonarVision.cpp \
	Player.cpp \
	PlayerInput.cpp \
	PlayerMovement.cpp \
	PlayerMovementController.cpp \
	PlayerNavPath.cpp \
	PlayerNavPathAgent.cpp \
	PlayerNavPathGraph.cpp \
	PlayerNavPathPoint.cpp \
	PlayerNavPathTagPointCloud.cpp \
	PlayerRotation.cpp \
	HUD/HUD_ASScoreElement.cpp \
	HUD/HUD_CDScoreElement.cpp \
	HUD/HUD_CTFScoreElement.cpp \
	HUD/HUD_IAScoreElement.cpp \
	HUD/Objects/HUD_LeavingBattle.cpp \
	HUD/HUD_Message.cpp \
	HUD/HUD_MPSelectMenu.cpp \
	HUD/HUD_PSLScoreElement.cpp \
	HUD/HUD_ReviveCycle.cpp \
	HUD/HUD_Scoreboard.cpp \
	HUD/HUD_TIAScoreElement.cpp \
	HUD/HUD_Vehicles.cpp \
	Menus/FlashMenuButtonHandler.cpp \
	Network/Lobby/GameLobby.cpp \
	StatHelpers.cpp \
	StatsRecordingMgr.cpp \
	TelemetryCollector.cpp \
	XMLStatsSerializer.cpp \
	Graphics/ColorGradientManager.cpp \
	Menus/CreateGame.cpp \
	Menus/FlashMenuObject.cpp \
	Menus/FlashMenuObjectOptions.cpp \
	Menus/FlashMenuObjectProfiles.cpp \
	Menus/FlashMenuObjectSingleplayer.cpp \
	Menus/FlashMenuScreen.cpp \
	Menus/GameNetworkProfile.cpp \
	Menus/MPHub.cpp \
	Menus/MPLobbyUI.cpp \
	Menus/MultiplayerMenu.cpp \
	Menus/OptionsManager.cpp \
	Menus/QuickGame.cpp \
	AI/AdvantagePointOccupancyControl.cpp \
	AI/AIAggression.cpp \
	AI/AIBattleFront.cpp \
	AI/AIPressure.cpp \
	GameAIInstanceBase.cpp \
	AI/GameAISystem.cpp \
	AI/ScriptBind_GameAI.cpp \
	AI/TacticalPointLanguageExtender.cpp \
	CheckpointGame.cpp \
	Boids/BoidsProxy.cpp \
	Boids/BugsFlock.cpp \
	Boids/ChickenBoids.cpp \
	Boids/Flock.cpp \
	Boids/FrogBoids.cpp \
	Boids/ScriptBind_Boids.cpp \
	GameMechanismManager/GameMechanismBase.cpp \
	GameMechanismManager/GameMechanismManager.cpp \
	Network/Lobby/CryLobbySessionHandler.cpp \
	GameStateRecorder.cpp \
	VehicleActionEntityAttachment.cpp \
	VehicleActionLandingGears.cpp \
	FlowItemAnimation.cpp \
	Item.cpp \
	ItemAccessory.cpp \
	ItemClientServer.cpp \
	ItemDualWield.cpp \
	ItemEffect.cpp \
	ItemEvents.cpp \
	ItemParams.cpp \
	ItemResource.cpp \
	ItemScheduler.cpp \
	ItemView.cpp \
	ScriptBind_Item.cpp \
	AmmoParams.cpp \
	Projectile.cpp \
	Recoil.cpp \
	ScriptBind_Weapon.cpp \
	TracerManager.cpp \
	Weapon.cpp \
	WeaponClientServer.cpp \
	WeaponEvent.cpp \
	WeaponInput.cpp \
	WeaponSystem.cpp \
	Automatic.cpp \
	LTAGGrenade.cpp \
	Rock.cpp \
	Rocket.cpp \
	TacBullet.cpp \
	TagBullet.cpp \
	IronSight.cpp \
	Scope.cpp \
	AIGrenade.cpp \
	AmmoPickup.cpp \
	Binocular.cpp \
	C4.cpp \
	DebugGun.cpp \
	GunTurret.cpp \
	HandGrenades.cpp \
	HMG.cpp \
	JAW.cpp \
	LTAG.cpp \
	PickAndThrowWeapon.cpp \
	ReferenceWeapon.cpp \
	ThrowableWeapon.cpp \
	VehicleHMG.cpp \
	VehicleWeapon.cpp \
	Accessory.cpp \
	Flashlight.cpp \
	Laser.cpp \
	SelfDestructPerk.cpp \
	SilentFeetPerk.cpp \
	StampPerk.cpp \
	ThreatDetectorPerk.cpp \
	TrackerPerk.cpp \
	Battlechatter.cpp \
	EquipmentLoadout.cpp \
	TeamPerks.cpp \
	GameRulesModules/GameRulesAssistScoring.cpp \
	GameRulesModules/GameRulesModulesManager.cpp \
	GameRulesModules/GameRulesMPActorAction.cpp \
	GameRulesModules/GameRulesMPDamageHandling.cpp \
	GameRulesModules/GameRulesMPHQFrontlineSpawning.cpp \
	GameRulesModules/GameRulesMPSimpleSpawning.cpp \
	GameRulesModules/GameRulesMPSpawning.cpp \
	GameRulesModules/GameRulesMPSpawningWithLives.cpp \
	GameRulesModules/GameRulesMPSpectator.cpp \
	GameRulesModules/GameRulesObjectiveVictoryConditionsTeam.cpp \
	GameRulesModules/GameRulesProgressiveObjectives.cpp \
	GameRulesModules/GameRulesSpawningBase.cpp \
	GameRulesModules/GameRulesStandardPlayerStats.cpp \
	GameRulesModules/GameRulesStandardRounds.cpp \
	GameRulesModules/GameRulesStandardScoring.cpp \
	GameRulesModules/GameRulesStandardSetup.cpp \
	GameRulesModules/GameRulesStandardState.cpp \
	HUD/HUDStateManager.cpp \
	HUD/HUDTester.cpp \
	HUD/ScreenLayoutManager.cpp \
	HUD/ScreenLayoutUtils.cpp \
	HUD/UI/UIElementFactory.cpp \
	HUD/UIElementManager.cpp \
	HUD/UI/UIBattleLog.cpp \
	HUD/UI/UIButtonPromptRegion.cpp \
	HUD/UI/UICoverEntireScreen.cpp \
	HUD/UI/UIDeathCam.cpp \
	HUD/UI/UIElement.cpp \
	HUD/UI/UIHitIndicators.cpp \
	HUD/UI/UIImageElement.cpp \
	HUD/UI/UIMinimapTextureElement.cpp \
	HUD/UI/UINewDamageIndicator.cpp \
	HUD/UI/UIObjectives.cpp \
	HUD/UI/UIPerkIconSet.cpp \
	HUD/UI/UIPrematch.cpp \
	HUD/UI/UIScorePopup.cpp \
	HUD/UI/UISimpleBar.cpp \
	HUD/UI/UISpectatorCam.cpp \
	HUD/UI/UISubElement.cpp \
	HUD/UI/UITagNames.cpp \
	HUD/UI/UITextElement.cpp \
	HUD/HUD_AONScoreElement.cpp \
	Nodes/FlowCoopNodes.cpp \
	Nodes/FlowHitInfoNode.cpp \
	Nodes/FlowNanoSuitNodes.cpp \
	Nodes/FlowNodesInput.cpp \
	Nodes/FlowPlayerStagingNode.cpp \
	Nodes/FlowPostFXNodes.cpp \
	FlowVehicleNodes.cpp \
	Nodes/G2FlowEntityElectricConnector.cpp \
	Nodes/G2FlowEntityVelocity.cpp \
	Nodes/G2FlowYesNoGestureNode.cpp \
	Nodes/HUDNodes.cpp \
	Nodes/MPNodes.cpp \
	Nodes/WeaponNodes.cpp \
	Flash/Flash.cpp \
	FlashAnimation.cpp \
	LCD/EZ_LCD.cpp \
	LCD/EZ_LCD_Page.cpp \
	LCD/LCDAnimatedBitmap.cpp \
	LCD/LCDBase.cpp \
	LCD/LCDBitmap.cpp \
	LCD/LCDCollection.cpp \
	LCD/LCDGfx.cpp \
	LCD/LCDIcon.cpp \
	LCD/LCDManager.cpp \
	LCD/LCDOutput.cpp \
	LCD/LCDProgressBar.cpp \
	LCD/LCDScrollingText.cpp \
	LCD/LCDStreamingText.cpp \
	LCD/LCDText.cpp \
	LCD/LCDWrapper.cpp \
	Editor/GameRealtimeRemoteUpdate.cpp \
	FrontEnd/FlashFrontEnd.cpp \
	FrontEnd/FrontEnd.cpp \
	FrontEnd/FrontEndAudio.cpp \
	FrontEnd/FrontEndElement.cpp \
	FrontEnd/FrontEndParser.cpp \
	FrontEnd/FrontEndScreen.cpp \
	FrontEnd/ILoadingMessageProvider.cpp \
	FrontEnd/MenuData.cpp \
	FrontEnd/Option.cpp \
	FrontEnd/ProfileOptions.cpp \
	FrontEnd/WarningsManager.cpp \
	FrontEnd/Multiplayer/MPMenuHub.cpp \
	FrontEnd/Multiplayer/UIServerList.cpp \
	RecordingBuffer.cpp \
	RecordingSystem.cpp \
	BTBBomb.cpp \
	Dogtag.cpp \
	Javelin.cpp \
	SuitDisruptionField.cpp \
	GunTurret_AimWhereControllingPlayerIsAiming.cpp \
	WeaponWithPickupTimer.cpp \
	Chaff.cpp \
	EMPStrike.cpp \
	JavelinMissile.cpp \
	KVoltBullet.cpp \
	SatelliteStrike.cpp \
	TunnelingGrenade.cpp \
	VolatileSpike.cpp \
	FM_Hologram.cpp \
	FM_TunnellingGrenade.cpp \
	ActorHitReactController.cpp \
	DummyPlayer.cpp \
	IPerk.cpp \
	Perk.cpp \
	PerkCommands.cpp \
	PerkDbgDisplay.cpp \
	PerkUnitTests.cpp \
	PersistantStats.cpp \
	PlayerHologram.cpp \
	PlayerModifiableValues.cpp \
	PlayerPerkParticleInfo.cpp \
	PlayerPlugin.cpp \
	PlayerPlugin_CurrentlyTargetting.cpp \
	PlayerPlugin_Interaction.cpp \
	PlayerPlugin_ScoreRewards.cpp \
	PlayerProgression.cpp \
	SkeletonAlignedParticleCreator.cpp \
	SkillKill.cpp \
	SuitModeProgression.cpp \
	DualCharacterProxy.cpp \
	IKTorsoAim_Helper.cpp \
	LookAim_Helper.cpp \
	TransformationPinning.cpp \
	WeaponFPAiming.cpp \
	CloakAwarenessPerk.cpp \
	CriticalEMPPerk.cpp \
	EagleVisionPerk.cpp \
	EMPStrikePerk.cpp \
	FatalityBonus.cpp \
	MissileCountermeasuresPerk.cpp \
	PerkIconData.cpp \
	PhantomPerk.cpp \
	PlayerPlugin_Perk_AutoTarget.cpp \
	PlayerPlugin_Perk_ModifyDamageBasedOnAngle.cpp \
	PlayerPlugin_Perk_ModifyValues.cpp \
	PlayerPlugin_Perk_SniperCountermeasures.cpp \
	PlayerPlugin_Perk_TeamPerkWithTimeout.cpp \
	ProximityPerk.cpp \
	ResistantPerk.cpp \
	GameRulesModules/GameRulesStandardTwoTeams.cpp \
	GameRulesModules/GameRulesStandardVictoryConditionsPlayer.cpp \
	GameRulesModules/GameRulesStandardVictoryConditionsTeam.cpp \
	GameRulesModules/GameRulesStatsRecording.cpp \
	GameRulesModules/GameRulesSurvivorOneVictoryConditions.cpp \
	GameRulesModules/GameRulesCaptureObjective.cpp \
	GameRulesModules/GameRulesCarryObjective.cpp \
	GameRulesModules/GameRulesCombiCaptureObjective.cpp \
	GameRulesModules/GameRulesHoldObjectiveBase.cpp \
	GameRulesModules/GameRulesKillObjective.cpp \
	GameRulesModules/GameRulesKingOfTheHillObjective.cpp \
	GameRulesModules/GameRulesLuaEntityObjective.cpp \
	GameRulesModules/GameRulesLuaObjectives.cpp \
	GameRulesModules/GameRulesObjectiveHelper_Carry.cpp \
	GameRulesModules/GameRulesObjectiveHelper_Icon.cpp \
	GameRulesModules/GameRulesObjectiveHelper_NeutralSpawn.cpp \
	GameRulesModules/GameRulesObjectiveHelper_Spawn.cpp \
	GameRulesModules/GameRulesSimpleEntityBasedObjective.cpp \
	GameRulesModules/GameRulesLuaListener.cpp \
	Testing/AutoTester.cpp \
	Testing/FeatureTester.cpp \
	AutoEnum.cpp \
	Utility/CryHash.cpp \
	Utility/CryWatch.cpp \
	Utility/DesignerWarning.cpp \
	StdAfx.cpp \
	HUD/HUD_EnergyAndSuitMode.cpp \
	HUD/HUD_InformationField.cpp \
	HUD/HUD_Interactive.cpp \
	HUD/HUD_InteractWithObject.cpp \
	HUD/HUD_InterestPoints.cpp \
	HUD/HUD_Logic.cpp \
	HUD/HUD_LookAtUpdater.cpp \
	HUD/HUD_NavPath.cpp \
	HUD/HUD_ObjectiveDisplay.cpp \
	HUD/HUD_Radar.cpp \
	HUD/HUD_ScannedEnemiesUpdater.cpp \
	HUD/HUD_SuitMenu.cpp \
	HUD/HUD_TacticalInfo.cpp \
	HUD/HUD_UnifiedAsset.cpp \
	HUD/HUD_Video.cpp \
	HUD/HUD_Visor.cpp \
	HUD/HUD_WeaponSelect.cpp \
	GameRules.cpp \
	GameRulesClientServer.cpp \
	ScriptBind_GameRules.cpp \
	Nodes/AINodes.cpp \
	Nodes/ColorGradientNode.cpp \
	Nodes/FlowActorNodes.cpp \
	Nodes/FlowActorSensor.cpp \
	Nodes/FlowConvoyNode.cpp \
	RecursiveDimensionalClustering.cpp \
	Utility/SingleAllocTextBlock.cpp \
	SShootHelper.cpp \
	Utility/StringUtils.cpp \
	Effects/GameEffectsSystem.cpp \
	Effects/RenderElements/CREScreenFilter.cpp \
	Effects/RenderNodes/ScreenFilterRenderNode.cpp \
	Effects/GameEffects/CCTVGameEffect.cpp \
	Effects/GameEffects/DeflectionGameEffect.cpp \
	Effects/GameEffects/ExplosionGameEffect.cpp \
	Effects/GameEffects/GameEffect.cpp \
	Effects/GameEffects/HitRecoilGameEffect.cpp \
	Effects/HUDEventListeners/CCTVHudEventListener.cpp \
	Effects/Tools/CVarActivationSystem.cpp \
	Effects/Tools/PostEffectActivationSystem.cpp \
	GameCodeCoverage/GameCodeCoverageGUI.cpp \
	GameCodeCoverage/GameCodeCoverageManager.cpp \
	GameCodeCoverage/GameCodeCoverageTracker.cpp \
	GameCodeCoverage/IGameCodeCoverageListener.cpp \
	Audio/Announcer.cpp \
	HUD/HUDControllerInputIcons.cpp \
	HUD/HUDOnScreenMessageDef.cpp \
	Graphics/2DRenderUtils.cpp \
	HUD/ColourFromXML.cpp \
	HUD/HUDObjectManager.cpp \
	AutomaticShotgun.cpp \
	Burst.cpp \
	Charge.cpp \
	Detonate.cpp \
	ImpulseBeam.cpp \
	LTagSingle.cpp \
	Melee.cpp \
	MikeBullet.cpp \
	PingerDetectorBurst.cpp \
	Plant.cpp \
	Rapid.cpp \
	Shotgun.cpp \
	Single.cpp \
	SniperSingle.cpp \
	Throw.cpp \
	ThrowEx.cpp \
	AVMine.cpp \
	Bullet.cpp \
	C4Projectile.cpp \
	Claymore.cpp \
	EMPField.cpp \
	Grenade.cpp \
	HomingMissile.cpp \
	ImpulseBeamProjectile.cpp \
	GameForceFeedback.cpp \
	LaptopUtil.cpp \
	NetInputChainDebug.cpp \
	ScriptUtils.cpp \
	StatsAgent.cpp \
	HUD/ContextualInfo.cpp \
	HUD/GameFlashAnimation.cpp \
	HUD/GameFlashLogic.cpp \
	HUD/HUD.cpp \
	HUD/HUD_Impl.cpp \
	HUD/HUDAsset.cpp \
	HUD/HUDCVars.cpp \
	HUD/HUDEventDispatcher.cpp \
	HUD/HUDEventTranslator.cpp \
	HUD/HUDMissionObjectiveSystem.cpp \
	HUD/HUDObject.cpp \
	HUD/HUDObjectFactory.cpp \
	HUD/HUDSilhouettes.cpp \
	HUD/HUDState.cpp \
	HUD/LocalizedStringManager.cpp \
	HUD/ScriptBind_HUD.cpp \
	HUD/HUD_AIUpdater.cpp \
	HUD/HUD_Ammo.cpp \
	HUD/HUD_Crosshair.cpp \
	HUD/HUD_Debug.cpp \

PROJECT_SOURCES_CPP_ADD += \
	uberfiles/Game03_1_uber.cpp \
	uberfiles/Game03_2_uber.cpp \
	uberfiles/Game03_3_uber.cpp \
	uberfiles/Game03_4_uber.cpp \
	uberfiles/Game03_0_uber.cpp \
	uberfiles/Game03_18_uber.cpp \
	uberfiles/Game03_19_uber.cpp \
	uberfiles/Game03_5_uber.cpp \
	uberfiles/Game03_7_uber.cpp \
	uberfiles/Game03_14_uber.cpp \
	uberfiles/Game03_17_uber.cpp \
	uberfiles/Game03_10_uber.cpp \
	uberfiles/Game03_11_uber.cpp \
	uberfiles/Game03_12_uber.cpp \
	uberfiles/Game03_13_uber.cpp \
	uberfiles/Game03_15_uber.cpp \
	uberfiles/Game03_20_uber.cpp \
	uberfiles/Game03_9_uber.cpp \
	uberfiles/Game03_16_uber.cpp \
	uberfiles/Game03_6_uber.cpp \
	uberfiles/Game03_8_uber.cpp \

endif

		
# vim:ts=8:sw=8
