#ifndef __CRYDXPSGCM_FORMATS__
#define __CRYDXPSGCM_FORMATS__

SPU_LOCAL extern uint32 DXGI_FORMAT2GCM[];
SPU_LOCAL extern uint8	GCM_TEXTUREFORMAT_SIZE[];
extern uint8	GCM_TEXTUREFORMAT2SURFACEFORMAT[];

#define GCM_TextureFormatSize(S,X) (((S)*GCM_TEXTUREFORMAT_SIZE[((X)&~(CELL_GCM_TEXTURE_LN|CELL_GCM_TEXTURE_UN))-0x81])>>1)
#define GCM_TextureFormat2SurfaceFormat(X) GCM_TEXTUREFORMAT2SURFACEFORMAT[(X)-0x81]

#endif

