///////////////////////////////////////////////////////////////////////////
//
//  Crytek Engine Source File.
//  Copyright (C), Crytek Studios, 2001-2009.
// -------------------------------------------------------------------------
//  File name:   LMG_Types.h
//  Version:     v1.00
//  Created:     07/07/2009 by Jaewon Jung
//  Description: Locomotion Group Types
// -------------------------------------------------------------------------
//
///////////////////////////////////////////////////////////////////////////

//// DRY = Don't Repeat Yourself 
DRY(STF1)		// Strafing with 4 directions
DRY(UDH1)		// A standard turn-left/turn-right and uphill/downhill, with one speed
DRY(M2I1)		// Move2Idle with 1 speed
DRY(I2M1)		// Idle2Move with 1 speed
DRY(TRN1)		// Turn with 1 speed
DRY(FLR1)		// Forward-Left-Right in 1 speed
DRY(S__1)		// Strafing with 6-direction assets
DRY(M__1)		// Strafing with 8-direction assets
DRY(SUD2)		// Strafing with Uphill/Downhill in 2 speeds
DRY(STF2)		// Strafing with 8 assets in 2 speeds
DRY(UDH2)		// A standard turn-left/turn-right and uphill/downhill, with two speeds
DRY(STH2)		// Strafing with 6-direction/3 forward speeds assets/2 direction speeds/left-right turns/uphill-downhill
DRY(S_H2)		// Strafing with 6-direction/2 direction speeds/uphill-downhill
DRY(I2M2)		// Idle2Move with 2 speeds
DRY(XIM2)		// Idle2Move with 2 speed
DRY(FLR2)		// Forward-Left-Right in 2 speeds
DRY(WFW2)		// Just 2 speeds
DRY(ST_2)		// Strafing with 6-direction/3 forward speeds assets/2 direction speeds/left-right turns
DRY(S__2)		// Strafing with 6-direction and 2 speeds assets
DRY(UDH3)		// A standard turn-left/turn-right and uphill/downhill, with three speeds
DRY(FLR3)		// Forward-Left-Right in 3 speeds
DRY(RFW3)		// Just 3 speeds
DRY(T_IA)		// Tactical idle aiming
DRY(CLMB)		// 
DRY(PUSH)		// 
DRY(SCAL)		// LMG for scale-dependent animations
DRY(COOP)		// LMG for coop moves
DRY(ISTP)		// Idle Step
DRY(TSTP)		// Idle rotation
DRY(T_IS)		// ISTP for tactical moves
DRY(T_WS)		// S__1 for tactical moves
DRY(IROT)		// Idle rotation
DRY(PROT)
DRY(STHX)		// Strafing with 4-direction/3 forward speeds assets/2 direction speeds/left-right turns/uphill-downhill
DRY(_TH2)