#############################################################################
## Crytek Source File
## Copyright (C) 2013, Crytek Studios
##
## Creator: Christopher Bolte
## Date: Oct 31, 2013
## Description: WAF  based build system
#############################################################################

def build(bld):	
	files = bld.read_file_list('assettaggingplugin.waf_files')

	bld.CryPlugin(
		target = 'AssetTagging',
		source = files,		
		includes = bld.CreateRootRelativePath('Code/Tools/AssetTagging/AssetTagging/'),							
		libpath = bld.CreateRootRelativePath('Code/Tools/AssetTagging/Release/x64'),					
		lib = 'AssetTaggingTools'
	)