//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Resource.rc
//
#define IDB_SCHEMATYC_BROWSER_ICONS     102
#define IDD_SCHEMATYC_CREATE_SIGNAL     103
#define IDR_SCHEMATYC_TOOLBAR           104
#define IDR_SCHEMATYC_MENU              110
#define IDD_SCHEMATYC_CREATE_DOC        312
#define IDD_SCHEMATYC_CREATE_SCHEMA     313
#define IDD_SCHEMATYC_ADD_STATE         314
#define IDD_SCHEMATYC_ADD_VARIABLE      315
#define IDD_SCHEMATYC_QUICK_SEARCH      317
#define IDD_SCHEMATYC_ADD_GRAPH         321
#define IDD_SCHEMATYC_ADD_ACTION        322
#define IDD_SCHEMATYC_ADD_GROUP         323
#define IDD_SCHEMATYC_ADD_TIMER         324
#define IDD_SCHEMATYC_ADD_COMPONENT     326
#define IDD_SCHEMATYC_ADD_GRAPH_NODE_OUTPUT 327
#define IDD_SCHEMATYC_ADD_ABSTRACT_INTERFACE 328
#define IDD_SCHEMATYC_ADD_STATE_MACHINE 329
#define IDD_SCHEMATYC_CREATE_ENUMERATION 332
#define IDD_SCHEMATYC_CREATE_STRUCTURE  333
#define IDD_SCHEMATYC_CREATE_ACTION     334
#define IDD_SCHEMATYC_PROPERTY_TREE     335
#define IDD_SCHEMATYC_ADD_CONTAINER     336
#define IDC_SCHEMATYC_DOC_NAME          1000
#define IDC_SCHEMATYC_SCHEMA_NAME       1001
#define IDC_SCHEMATYC_STATE_NAME        1002
#define IDC_SCHEMATYC_VARIABLE_NAME     1004
#define IDC_SCHEMATYC_VARIABLE_TYPES    1005
#define IDC_SCHEMATYC_QUICK_SEARCH_FILTER 1010
#define IDC_SCHEMATYC_SIGNAL_NAME       1018
#define IDC_SCHEMATYC_GRAPH_NAME        1023
#define IDC_SCHEMATYC_GROUP_NAME        1026
#define IDC_SCHEMATYC_SCHEMA_FOUNDATIONS 1028
#define IDC_SCHEMATYC_QUICK_SEARCH_TREE 1029
#define IDC_SCHEMATYC_TIMER_NAME        1031
#define IDC_SCHEMATYC_GRAPH_NODE_OUTPUTS 1039
#define IDD_SCHEMATYC_ABSTRACT_INTERFACES 1040
#define IDD_SCHEMATYC_ABSTRACT_INTERFACE_DESCRIPTION 1041
#define IDC_SCHEMATYC_STATE_MACHINE_NAME 1045
#define IDD_SCHEMATYC_COMPONENTS        1053
#define IDD_SCHEMATYC_COMPONENT_DESCRIPTION 1054
#define IDD_SCHEMATYC_ACTIONS           1055
#define IDD_SCHEMATYC_ACTION_DESCRIPTION 1056
#define IDD_SCHEMATYC_GRAPH_CONTEXTS    1057
#define IDC_SCHEMATYC_ENUMERATION_NAME  1058
#define IDC_SCHEMATYC_STRUCTURE_NAME    1059
#define IDD_SCHEMATYC_COMPONENT_NAME    1060
#define IDC_SCHEMATYC_ACTION_NAME       1062
#define IDD_SCHEMATYC_ACTION_NAME       1062
#define IDC_SCHEMATYC_STATE_MACHINE_LIFETIME 1063
#define IDC_SCHEMATYC_PROPERTY_TREE     1064
#define IDC_SCHEMATYC_CONTAINER_TYPES   1065
#define IDC_SCHEMATYC_CONTAINER_NAME    1066
#define ID_SCHEMATYC_SAVE               33630
#define ID_SCHEMATYC_REFRESH_ENV        40002
#define ID_SCHEMATYC_VIEW_BROWSER       40010
#define ID_SCHEMATYC_VIEW_ENV_BROWSER   40011
#define ID_SCHEMATYC_VIEW_DETAIL        40013
#define ID_SCHEMATYC_VIEW_GRAPH         40014
#define ID_SCHEMATYC_VIEW_COMPILER_OUTPUT 40016
#define ID_SCHEMATYC_VIEW_VIEWPORT      40017
#define ID_SCHEMATYC_TOOLS_CONFIGURE_LOG_STREAMS 40030
#define ID_SCHEMATYC_VIEW_LOG_OUTPUT_A  40032
#define ID_SCHEMATYC_VIEW_LOG_OUTPUT_C  40033
#define ID_SCHEMATYC_VIEW_LOG_OUTPUT_D  40034
#define ID_SCHEMATYC_VIEW_LOG_OUTPUT_B  40035
#define ID_SCHEMATYC_TOOLS_CONFIGURE_LOG_OUTPUT_A 40040
#define ID_SCHEMATYC_TOOLS_CONFIGURE_LOG_OUTPUT_B 40041
#define ID_SCHEMATYC_TOOLS_CONFIGURE_LOG_OUTPUT_C 40042
#define ID_SCHEMATYC_TOOLS_CONFIGURE_LOG_OUTPUT_D 40043
#define ID_SCHEMATYC_DEBUG_SELECTED_ENTITY 40045
#define ID_SCHEMATYC_WORLD_DEBUG_SHOW_STATES 40054
#define ID_SCHEMATYC_WORLD_DEBUG_SHOW_VARIABLES 40062
#define ID_SCHEMATYC_WORLD_DEBUG_SHOW_TIMERS 40063
#define ID_SCHEMATYC_WORLD_DEBUG_SHOW_ACTIONS 40064
#define ID_SCHEMATYC_ENTITY_DEBUG_SHOW_STATES 40065
#define ID_SCHEMATYC_ENTITY_DEBUG_SHOW_VARIABLES 40067
#define ID_SCHEMATYC_ENTITY_DEBUG_SHOW_ACTIONS 40068
#define ID_SCHEMATYC_ENTITY_DEBUG_SHOW_TIMERS 40069
#define ID_SCHEMATYC_ENTITY_DEBUG_SHOW_SIGNAL_HISTORY 40072
#define ID_SCHEMATYC_WORLD_DEBUG_SHOW_SIGNAL_HISTORY 40073
#define ID_ENTITY_SHOWCONTAINERS        40074
#define ID_SCHEMATYC_ENTITY_DEBUG_SHOW_CONTAINERS 40075
#define ID_WORLD_SHOWCONTAINERS         40076
#define ID_SCHEMATYC_WORLD_DEBUG_SHOW_CONTAINERS 40077

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        112
#define _APS_NEXT_COMMAND_VALUE         40078
#define _APS_NEXT_CONTROL_VALUE         1067
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
