#############################################################################
## Crytek Source File
## Copyright (C) 2013, Crytek Studios
##
## Creator: Christopher Bolte
## Date: Oct 31, 2013
## Description: WAF  based build system
#############################################################################

def build(bld):
	files = bld.read_file_list('emergentplugin.waf_files')

	bld.CryPlugin(
		target = 'EmergentPlugin',
		source = files,
		pch = 'stdafx.cpp',
		includes = '../../',
		use = 'Editor'
	)